# Generated by Django 3.2.13 on 2022-07-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220516_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='item2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='item3',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
