# Generated by Django 3.2.13 on 2022-07-15 17:26

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp_v10', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='banner_title10',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-4  '),
        ),
        migrations.AddField(
            model_name='home',
            name='banner_title11',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-4  '),
        ),
        migrations.AddField(
            model_name='home',
            name='banner_title8',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-4  '),
        ),
        migrations.AddField(
            model_name='home',
            name='banner_title9',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-4  '),
        ),
    ]
