# Generated by Django 3.2.13 on 2022-07-15 20:44

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('webapp_v10', '0002_auto_20220715_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, verbose_name='to address')),
                ('from_address', models.CharField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('bio', wagtail.core.fields.RichTextField(blank=True, verbose_name='rseña bibliografica')),
                ('banner_title4', wagtail.core.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-1 ')),
                ('banner_title5', wagtail.core.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-2  ')),
                ('banner_title6', wagtail.core.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-3  ')),
                ('banner_title7', wagtail.core.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-4  ')),
                ('banner_title8', wagtail.core.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-4  ')),
                ('banner_title9', wagtail.core.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-4  ')),
                ('banner_title10', wagtail.core.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-4  ')),
                ('banner_title11', wagtail.core.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-4  ')),
                ('custom_title', models.CharField(blank=True, help_text='Reescribe el  Titulo de la publicacion ', max_length=100, null=True)),
                ('consulta', wagtail.core.fields.RichTextField(blank=True, verbose_name='Mensaje para que nos consulten por el formulario')),
                ('thank_you_text', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_10',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_11',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_12',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_13',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_14',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_15',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_16',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_17',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_18',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_19',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_20',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_21',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_22',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_23',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_24',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_25',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_26',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_27',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_7',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_8',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_9',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='consultas',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='webapp_v10.history'),
        ),
        migrations.AlterField(
            model_name='galeriadeimagenes',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleria_1', to='webapp_v10.history'),
        ),
    ]
