# Generated by Django 3.2.13 on 2022-07-15 20:45

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('webapp_v10', '0003_auto_20220715_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Tear-Sheet-3'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Tear-Sheet-4'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Tear-Sheet-5 '),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Tear-Sheet-6'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Tear-Sheet-7'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Tear-Sheet-8'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Tear-Sheet-9'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_17',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Tear-Sheet-10'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_18',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Tear-Sheet-11'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_19',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Tear-Sheet-12'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_20',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Tear-Sheet-13'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_21',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Tear-Sheet-14'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_22',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Tear-Sheet-15'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_23',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Tear-Sheet-16'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_24',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Tear-Sheet-17'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_25',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Tear-Sheet-18'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_26',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Tear-Sheet-19'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_27',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Tear-Sheet-20'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Landscape Thumb4-Galeria'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Tear-Sheet-1'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='image_9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Tear-Sheet-2'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes',
            name='profile_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='galeriadeimagenes',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleria', to='webapp_v10.home'),
        ),
        migrations.CreateModel(
            name='GaleriadeImagenes_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 1')),
                ('image_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 2')),
                ('image_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 3')),
                ('image_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Advertising Thumb-Galeria')),
                ('image_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Product Thumb2-Galeria')),
                ('image_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Documentary Thumb3-Galeria')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logotipo de Juan Silva Photo')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleria_1', to='webapp_v10.history')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
