# Generated by Django 3.2.13 on 2022-07-18 16:21

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('webapp_v10', '0006_charms_consultas_2_galeriadeimagenes_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='charms',
            name='banner_title12',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Titulo de galeria-4  '),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes_2',
            name='image_10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Product Thumb2-Galeria'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes_2',
            name='image_11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Documentary Thumb3-Galeria'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes_2',
            name='image_12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 2'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes_2',
            name='image_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 2'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes_2',
            name='image_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Slide Banner 3'),
        ),
        migrations.AddField(
            model_name='galeriadeimagenes_2',
            name='image_9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen Advertising Thumb-Galeria'),
        ),
    ]
