# Generated by Django 3.2.13 on 2022-06-07 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_10_2',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_4_2',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_5_2',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_6_2',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_7_2',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_8_2',
        ),
        migrations.RemoveField(
            model_name='galeriadeimagenes',
            name='image_9_2',
        ),
    ]
